### ISSUE TITLE
Bacmet error : cat: ecoli_bacmet.bacmet.report.temp: No such file or directory

### ISSUE THREAD

**Issue by DehuryB** [ZhihaoXie/BacMet#1]
I am trying to run bacmet as suggested in the test example but while running its showing the following error:

cat: ecoli_bacmet.bacmet.report.temp: No such file or directory

**Comment by ZhihaoXie** [comment]
> 
> 
> I am trying to run bacmet as suggested in the test example but while running its showing the following error:
> 
> cat: ecoli_bacmet.bacmet.report.temp: No such file or directory

How do you run BacMet? What are the input and parameters? Prompt "No to the file or directory" is generally program mistakes can't find the corresponding file.

**Comment by DehuryB** [comment]
perl ./BacMet-Scan_v1.1.pl -i ecoli_protein.fa -o ecoli_bacmet -d ./BacMet2_PRE -diamond -protein -cpu 10 -e 1e-5 -p 80 -all -columns all

The test file I ran it shows the following error:
cat: ecoli_bacmet.bacmet.report.temp: No such file or directory..There is some problem with 'temp' setting in the perl script.

Please check and let me know..I have downloaded the total Bacmet folder from your github account and ran the test file

Thanks and regards
Budheswar
[test_1.zip](https://github.com/ZhihaoXie/BacMet/files/7189145/test_1.zip)

**Comment by ZhihaoXie** [comment]
> 
> 
> perl ./BacMet-Scan_v1.1.pl -i ecoli_protein.fa -o ecoli_bacmet -d ./BacMet2_PRE -diamond -protein -cpu 10 -e 1e-5 -p 80 -all -columns all
> 
> The test file I ran it shows the following error:
> cat: ecoli_bacmet.bacmet.report.temp: No such file or directory..There is some problem with 'temp' setting in the perl script.
> 
> Please check and let me know..I have downloaded the total Bacmet folder from your github account and ran the test file
> 
> Thanks and regards
> Budheswar
> [test_1.zip](https://github.com/ZhihaoXie/BacMet/files/7189145/test_1.zip)

ecoli_bacmet.bacmet.report.temp generated by diamond, ensure that the diamond in bacmet directory or in the PATH, and has an executable permissions. You can run `ls -lh./BacMet` or `which diamond` to see if you downloaded the total Bacmet folder from my github.

**Comment by DehuryB** [comment]
the diamond version which you have in your github profile from bacmet folder, I have the same in my bacmet directory. 

which diamond
/home/hp/miniconda3/bin/diamond

I think there was a problem with the permission of using diamond.. Thanks a lot for solving this error..
With regards
Budheswar

**Comment by shenghuanjing** [comment]
Hello,
I encountered an error when running the FORLoop, but no error will be reported when running a single command without using a for loop..  So I specifically ask for advice.

This command runs smoothly:  perl ../BacMet-Scan_v1.1.pl -i assembly.fasta -o test_bacmet -d ../BacMet2_EXP -diamond -cpu 10 -matrix -counts

The for loop error is as follows: 
$ for i in *.fasta; do perl ../BacMet-Scan_v1.1.pl -i $i -o $i_bacmet -d ../BacMet2_EXP -diamond -cpu 10 -matrix -counts; done
ERROR! The BacMet database could not be found.
Expected to find it in PRE
Consult the manual for installation instructions.
-----------------------------------------------------------------
Thanks and regards
Huanjing
